### ISSUE TITLE
Just to understand a little better.

### ISSUE THREAD

**Issue by ewerlopes** [miccol/ROS-Behavior-Tree#1]
Hi again.

So, I have been trying to understand this code. Can you please tell me what is the **src.zip** in the **src** directory? I mean, why there is a **.zip** there? And else.. can you tell me where is the **BTAction.h** located? I see the following inclusion in a bunch of source files but I am not able to locate the corresponding file:

`#include <behavior_tree_leaves/BTAction.h>`

Can you help me on this?
Regards. Thanks a lot.

**Comment by miccol** [comment]
Hi,

I have removed the src.zip file. It was a backup file and for some reason git did not ignore it even though I set it to ignore (thanks for spotting this).

BTAction.h is (self) generated when compiled using catkin_make (This is the ROS version)

If you take a look at the CMakeLists you will see at line 73:

add_action_files(
  DIRECTORY action
  FILES BT.action ObjectsList.action Detector.action
)

(I should remove ObjectList and Detector since I am not using them in the example anymore but nevermind.)

For every file XXX.action ROS, in particular the actionlib library, creates the XXX.h header.

For more details see: http://wiki.ros.org/actionlib

**Comment by ewerlopes** [comment]
Hi,

Thanks for replying! 
Cool! I suspected that had to be related with ROS somehow. I have to take a look at actionlib and see how this code rely on it.

Well, I have created a dev branch in my fork. On it I try to separate the lib code from the example code. It is really hard to see when they are mixed up.

But, anyway.. Thank you again for your reply.
Best regards.

**Comment by miccol** [comment]
Cool, let me know when you are done. I also have to change some minor stuff in the CMakeList

**Comment by ewerlopes** [comment]
Okay. I will try to see this and by tomorrow I should be "pull-requesting" something for your evaluation.

Once again, thank you very much!

**Comment by miccol** [comment]
Well, thank you for the suggestions and improvements.
